version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - chmod +x ./gradlew
      - ./gradlew clean test --info
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - ./gradlew explodedWar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: build/exploded
  files:
      - '**/*'
